[2025-03-05T23:11:28.293+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T23:11:28.298+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_stock_data.load_to_snowflake manual__2025-03-05T23:11:26.374669+00:00 [queued]>
[2025-03-05T23:11:28.300+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_stock_data.load_to_snowflake manual__2025-03-05T23:11:26.374669+00:00 [queued]>
[2025-03-05T23:11:28.300+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-05T23:11:28.304+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_to_snowflake> on 2025-03-05 23:11:26.374669+00:00
[2025-03-05T23:11:28.307+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=733) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T23:11:28.307+0000] {standard_task_runner.py:72} INFO - Started process 736 to run task
[2025-03-05T23:11:28.307+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_stock_data', 'load_to_snowflake', 'manual__2025-03-05T23:11:26.374669+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/extract_stock_data.py', '--cfg-path', '/tmp/tmpuun90_k_']
[2025-03-05T23:11:28.308+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask load_to_snowflake
[2025-03-05T23:11:28.322+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_stock_data.load_to_snowflake manual__2025-03-05T23:11:26.374669+00:00 [running]> on host 48a2c6bad219
[2025-03-05T23:11:28.351+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_stock_data' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T23:11:26.374669+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T23:11:26.374669+00:00'
[2025-03-05T23:11:28.352+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T23:11:28.356+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-05T23:11:28.356+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-03-05T23:11:28.356+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T23:11:28.356+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T23:11:29.002+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:29.094+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:29.318+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:29.321+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-05T23:11:29.321+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-03-05T23:11:29.321+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T23:11:29.321+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T23:11:29.672+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:29.672+0000] {sql.py:509} INFO - Running statement: PUT 'file:///tmp/GOOGL_data.csv' @dev.raw.stock_stage/GOOGL_data.csv AUTO_COMPRESS=TRUE OVERWRITE=TRUE, parameters: None
[2025-03-05T23:11:30.118+0000] {sql.py:518} INFO - Rows affected: 1
[2025-03-05T23:11:30.118+0000] {snowflake.py:422} INFO - Rows affected: 1
[2025-03-05T23:11:30.118+0000] {snowflake.py:423} INFO - Snowflake query id: 01bad06f-0004-b52e-0000-0005a9f7def9
[2025-03-05T23:11:30.320+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:30.320+0000] {connection.py:788} INFO - closed
[2025-03-05T23:11:30.376+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-03-05T23:11:30.816+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:31.751+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:32.979+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:32.980+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-03-05T23:11:32.980+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T23:11:32.980+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T23:11:33.390+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:33.391+0000] {sql.py:509} INFO - Running statement: PUT 'file:///tmp/TSLA_data.csv' @dev.raw.stock_stage/TSLA_data.csv AUTO_COMPRESS=TRUE OVERWRITE=TRUE, parameters: None
[2025-03-05T23:11:33.813+0000] {sql.py:518} INFO - Rows affected: 1
[2025-03-05T23:11:33.813+0000] {snowflake.py:422} INFO - Rows affected: 1
[2025-03-05T23:11:33.813+0000] {snowflake.py:423} INFO - Snowflake query id: 01bad06f-0004-b4f6-0000-0005a9f7e1c5
[2025-03-05T23:11:33.892+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:33.892+0000] {connection.py:788} INFO - closed
[2025-03-05T23:11:33.937+0000] {connection.py:794} INFO - No async queries seem to be running, deleting session
[2025-03-05T23:11:34.307+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:35.035+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:36.153+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:36.244+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:36.244+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T23:11:36.247+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T23:11:36.248+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_stock_data, task_id=load_to_snowflake, run_id=manual__2025-03-05T23:11:26.374669+00:00, execution_date=20250305T231126, start_date=20250305T231128, end_date=20250305T231136
[2025-03-05T23:11:36.284+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T23:11:36.291+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T23:11:36.292+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
