[2025-03-05T00:28:37.224+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T00:28:37.260+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_stock_data.fetch_stock_data scheduled__2025-03-03T09:00:00+00:00 [queued]>
[2025-03-05T00:28:37.282+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_stock_data.fetch_stock_data scheduled__2025-03-03T09:00:00+00:00 [queued]>
[2025-03-05T00:28:37.283+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-05T00:28:37.315+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): fetch_stock_data> on 2025-03-03 09:00:00+00:00
[2025-03-05T00:28:37.338+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_stock_data', 'fetch_stock_data', 'scheduled__2025-03-03T09:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/extract_stock_data.py', '--cfg-path', '/tmp/tmpdgdfjcxz']
[2025-03-05T00:28:37.350+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=294) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T00:28:37.354+0000] {standard_task_runner.py:72} INFO - Started process 297 to run task
[2025-03-05T00:28:37.355+0000] {standard_task_runner.py:105} INFO - Job 3: Subtask fetch_stock_data
[2025-03-05T00:28:37.595+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_stock_data.fetch_stock_data scheduled__2025-03-03T09:00:00+00:00 [running]> on host f0512e67eca3
[2025-03-05T00:28:37.933+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_stock_data' AIRFLOW_CTX_TASK_ID='fetch_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T09:00:00+00:00'
[2025-03-05T00:28:37.941+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T00:28:37.958+0000] {logging_mixin.py:190} INFO - YF.download() has changed argument auto_adjust default to True
[2025-03-05T00:28:37.981+0000] {cache.py:130} INFO - Failed to create TzCache, reason: Error creating TzCache folder: '/home/***/.cache/py-yfinance' reason: [Errno 17] File exists: '/home/***/.cache/py-yfinance'. TzCache will not be used. Tip: You can direct cache to use a different location with 'set_tz_cache_location(mylocation)'
[2025-03-05T00:28:39.879+0000] {logging_mixin.py:190} WARNING - [                       0%                       ]
[2025-03-05T00:28:39.894+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  2 of 2 completed
[2025-03-05T00:28:40.031+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_stock_data.py", line 31, in fetch_stock_data
    df.columns = ['symbol', 'date', 'open', 'high', 'low', 'close', 'volume']
    ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 4 elements, new values have 7 elements
[2025-03-05T00:28:40.092+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=extract_stock_data, task_id=fetch_stock_data, run_id=scheduled__2025-03-03T09:00:00+00:00, execution_date=20250303T090000, start_date=20250305T002837, end_date=20250305T002840
[2025-03-05T00:28:40.123+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T00:28:40.124+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task fetch_stock_data (Length mismatch: Expected axis has 4 elements, new values have 7 elements; 297)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_stock_data.py", line 31, in fetch_stock_data
    df.columns = ['symbol', 'date', 'open', 'high', 'low', 'close', 'volume']
    ^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 6218, in __setattr__
    return object.__setattr__(self, name, value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "properties.pyx", line 69, in pandas._libs.properties.AxisProperty.__set__
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 767, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/managers.py", line 227, in set_axis
    self._validate_set_axis(axis, new_labels)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/internals/base.py", line 85, in _validate_set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 4 elements, new values have 7 elements
[2025-03-05T00:28:40.188+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-05T00:28:40.273+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T00:28:40.285+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-05T04:43:54.059+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T04:43:54.163+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_stock_data.fetch_stock_data scheduled__2025-03-03T09:00:00+00:00 [queued]>
[2025-03-05T04:43:54.195+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_stock_data.fetch_stock_data scheduled__2025-03-03T09:00:00+00:00 [queued]>
[2025-03-05T04:43:54.197+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-05T04:43:54.245+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): fetch_stock_data> on 2025-03-03 09:00:00+00:00
[2025-03-05T04:43:54.417+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=420) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T04:43:54.698+0000] {standard_task_runner.py:72} INFO - Started process 443 to run task
[2025-03-05T04:43:54.440+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extract_stock_data', 'fetch_stock_data', 'scheduled__2025-03-03T09:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/extract_stock_data.py', '--cfg-path', '/tmp/tmpfoww615q']
[2025-03-05T04:43:54.821+0000] {standard_task_runner.py:105} INFO - Job 2: Subtask fetch_stock_data
[2025-03-05T04:43:56.267+0000] {task_command.py:467} INFO - Running <TaskInstance: extract_stock_data.fetch_stock_data scheduled__2025-03-03T09:00:00+00:00 [running]> on host 0d515916445a
[2025-03-05T04:43:56.950+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_stock_data' AIRFLOW_CTX_TASK_ID='fetch_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-03T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-03T09:00:00+00:00'
[2025-03-05T04:43:56.967+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T04:43:57.004+0000] {logging_mixin.py:190} INFO - YF.download() has changed argument auto_adjust default to True
[2025-03-05T04:43:58.598+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  1 of 1 completed
[2025-03-05T04:43:58.948+0000] {logging_mixin.py:190} WARNING - [*********************100%***********************]  1 of 1 completed
[2025-03-05T04:43:58.963+0000] {python.py:240} INFO - Done. Returned value was: ['/tmp/AAPL_data.csv', '/tmp/NVDA_data.csv']
[2025-03-05T04:43:59.319+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T04:43:59.320+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extract_stock_data, task_id=fetch_stock_data, run_id=scheduled__2025-03-03T09:00:00+00:00, execution_date=20250303T090000, start_date=20250305T044354, end_date=20250305T044359
[2025-03-05T04:43:59.441+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T04:43:59.548+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T04:43:59.555+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
